In this example, we will illustrate how user-defined exceptions can be used in a program to raise and catch errors.

This program will ask the user to enter a number until they guess a stored number correctly.
To help them figure it out, hint is provided whether their guess is greater than or less than the stored number.




Here, we have defined a base class called Error.

The other two exceptions (ValueTooSmallError and ValueTooLargeError) that are actually raised by our program are derived from this class.
This is the standard way to define user-defined exceptions in Python programming, but you are not limited to this way only.